server:
  port: 9002
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9002/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: false #关闭自我保护
spring:
  application:
    name: eureka-server